import { Experience } from "@/types/Expierence";
import { calculateJobLength } from "@/utils/calculateJobLength";

export const experience: Experience[] = [
  {
    id: 1,
    title: "Frontend Developer",
    description: "",
    job_type: "Freelance",
    job_icon: "/job_icons/freelance.svg",
    length: `${calculateJobLength("Jan 2025", "Present")} days`,
    company: "Freelance",
    startDate: "Jan 2025",
    endDate: "Present",
    location: "Remote",
    skills: [
      { id: 1, name: "React" },
      { id: 2, name: "Next.js" },
      { id: 3, name: "TypeScript" },
      { id: 4, name: "Tailwind CSS" },
      { id: 5, name: "tRPC" },
      { id: 6, name: "Docker" },
      { id: 7, name: "Git" },
      { id: 8, name: "GitHub" },
    ],
  },
  {
    id: 2,
    title: "Full Stack Developer",
    description: "",
    job_type: "Contract",
    job_icon: "/job_icons/intelliscreen.svg",
    length: `${calculateJobLength("Jul 2024", "Aug 2024")} months`,
    company: "Intelliscreen",
    startDate: "Jul 2024",
    endDate: "Aug 2024",
    location: "Remote",
    skills: [
      { id: 1, name: "Python" },
      { id: 2, name: "FastAPI" },
      { id: 3, name: "React" },
      { id: 4, name: "Next.js" },
      { id: 5, name: "JavaScript" },
      { id: 6, name: "Tailwind CSS" },
      { id: 7, name: "AWS" },
      { id: 8, name: "PostgreSQL" },
      { id: 9, name: "GCP" },
      { id: 10, name: "Docker" },
      { id: 11, name: "Git" },
      { id: 12, name: "GitHub" },
    ],
  },
  {
    id: 3,
    title: "Software Engineer",
    description: "",
    job_type: "Full-Time",
    job_icon: "/job_icons/accenture.png",
    length: `${calculateJobLength("Dec 2024", "Jul 2024")} months`,
    company: "Accenture",
    startDate: "Dec 2024",
    endDate: "Jul 2024",
    location: "Hybrid",
    skills: [
      { id: 1, name: "JAVA" },
      { id: 2, name: "Oracle DB" },
      { id: 3, name: "Azure" },
    ],
  },
  {
    id: 4,
    title: "Webmaster",
    description: "",
    job_type: "Full-Time",
    job_icon: "/job_icons/nespresso.svg",
    length: `${calculateJobLength("Sep 2022", "Aug 2023")} months`,
    company: "Nespresso",
    startDate: "Sep 2022",
    endDate: "Aug 2023",
    location: "Hybrid",
    skills: [
      { id: 1, name: "HTML" },
      { id: 2, name: "CSS" },
      { id: 3, name: "JavaScript" },
    ],
  },
];
